# Generated by Django 4.2.4 on 2023-12-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
