# Generated by Django 4.2.4 on 2023-12-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contacts_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
    ]
